project_name: {{ cookiecutter.project_slug }}
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: '{{ .ProjectName }}'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
dockers:
  - image_templates:
      - "public.ecr.aws/{{ cookiecutter.github_org }}/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Tag }}"
brews:
  - name: {{ .ProjectName }}
    homepage: "https://www.opslevel.com/"
    description: "{{ cookiecutter.project_description }}"
    license: "MIT"
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
    test: |
      system "#{bin}/{{ .ProjectName }} version"
    tap:
      owner: {{ cookiecutter.github_org }}
      name: homebrew-tap
      token: "{{ .Env.ORG_GITHUB_TOKEN }}"
checksum:
  name_template: '{{ .ProjectName }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
changelog:
  sort: desc
  filters:
    exclude:
      - "^Merge"
release:
  prerelease: auto
